import { TypographyOptions } from '@mui/material/styles/createTypography';

export default {
  h1: {
    fontFamily: "'Lato', sans-serif",
    fontWeight: 600,
    fontSize: '35px',
    letterSpacing: '-0.24px',
    lineHeight: '40px',
  },
  h2: {
    fontFamily: "'Lato', sans-serif",
    fontWeight: 600,
    fontSize: '29px',
    letterSpacing: '-0.24px',
    lineHeight: '32px',
  },
  h3: {
    fontFamily: "'Lato', sans-serif",
    fontWeight: 600,
    fontSize: '24px',
    letterSpacing: '-0.06px',
    lineHeight: '28px',
  },
  h4: {
    fontFamily: "'Lato', sans-serif",
    fontWeight: 600,
    fontSize: '20px',
    letterSpacing: '-0.06px',
    lineHeight: '24px',
  },
  h5: {
    fontFamily: "'Lato', sans-serif",
    fontWeight: 600,
    fontSize: '16px',
    letterSpacing: '-0.05px',
    lineHeight: '20px',
  },
  h6: {
    fontFamily: "'Lato', sans-serif",
    fontWeight: 600,
    fontSize: '15px',
    letterSpacing: '-0.05px',
    lineHeight: '20px',
  },
  subtitle1: {
    fontFamily: "'Lato', sans-serif",
    fontSize: '15px',
    letterSpacing: '-0.05px',
    lineHeight: '25px',
  },
  subtitle2: {
    fontFamily: "'Lato', sans-serif",
    fontWeight: 400,
    fontSize: '13px',
    letterSpacing: '-0.05px',
    lineHeight: '21px',
  },
  body1: {
    fontFamily: "'Lato', sans-serif",
    fontSize: '13px',
    letterSpacing: '-0.05px',
    lineHeight: '21px',
  },
  body2: {
    fontFamily: "'Lato', sans-serif",
    fontSize: '12px',
    letterSpacing: '-0.04px',
    lineHeight: '18px',
  },
  button: {
    fontFamily: "'Lato', sans-serif",
    fontSize: '13px',
    textTransform: 'none',
  },
  caption: {
    fontFamily: "'Lato', sans-serif",
    fontSize: '11px',
    letterSpacing: '0.33px',
    lineHeight: '13px',
  },
  overline: {
    fontFamily: "'Lato', sans-serif",
    fontSize: '11px',
    fontWeight: 500,
    letterSpacing: '0.33px',
    lineHeight: '13px',
    textTransform: 'uppercase',
  },
} as TypographyOptions;
